# Generated by Django 4.2.4 on 2024-03-10 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quiz_question', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text_A', models.CharField(default='Answer Text', max_length=255)),
                ('answer_text_B', models.CharField(default='Answer Text', max_length=255)),
                ('answer_text_C', models.CharField(default='Answer Text', max_length=255)),
                ('answer_text_D', models.CharField(default='Answer Text', max_length=255)),
                ('letter', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizquestion')),
            ],
        ),
    ]
