# Generated by Django 4.2.4 on 2024-03-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_code', models.CharField(max_length=10, unique=True)),
                ('host_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('players_scores', models.JSONField(blank=True, default=dict)),
                ('questions', models.ManyToManyField(to='quiz.quizquestion')),
            ],
        ),
    ]
