# Generated by Django 4.2.4 on 2024-03-10 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='game',
            new_name='game_code',
        ),
    ]
