# Generated by Django 4.2.4 on 2024-03-10 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_rename_game_player_game_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='game_code',
            new_name='game',
        ),
    ]
