# Generated by Django 4.2.4 on 2024-03-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_rename_game_code_player_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='players_scores',
        ),
        migrations.AddField(
            model_name='game',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
