# Generated by Django 4.2.4 on 2024-03-11 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_remove_game_players_scores_game_is_started'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerOrDrink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('AnswerOrDrinkQuestion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerOrDrinkPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerOrDrinkPlayerAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(choices=[('Pije', 'Piję'), ('Odpowiadam', 'Odpowiadam')], max_length=20)),
                ('AnswerOrDrinkQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.answerordrink')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.answerordrinkplayer')),
            ],
        ),
    ]
