# Generated by Django 4.2.4 on 2024-03-12 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_answerordrink_answerordrinkplayer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerordrinkplayeranswer',
            name='AnswerOrDrinkQuestion',
        ),
        migrations.RemoveField(
            model_name='answerordrinkplayeranswer',
            name='player',
        ),
        migrations.DeleteModel(
            name='AnswerOrDrinkPlayer',
        ),
        migrations.DeleteModel(
            name='AnswerOrDrinkPlayerAnswer',
        ),
    ]
