# Generated by Django 4.2.4 on 2024-03-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_remove_answerordrinkplayeranswer_answerordrinkquestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChineseProverb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChineseProverb', models.CharField(max_length=255)),
            ],
        ),
    ]
